name = "Heterotic"
uuid = "ad75e402-0094-4822-903c-3542ee61ae4f"
authors = ["jajapuramshivasai <jajapuramshivasai@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
